<?php
/**
 * @file
 * FAQ Field
 * Provides a field for frequently asked questions.
 */

/**
 * Implements hook_help().
 */
function faqfield_help($path, $arg) {
  switch ($path) {
    case 'admin/help#faqfield':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides a field for frequently asked questions. Added, you can create simple but smooth FAQs on any piece of content.') . '</p>';
      $output .= '<h3>' . t('Usage') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Configuration') . '</dt>';
      $output .= '<dd>' . t("No configuration needed.") . '</dd>';
      $output .= '<dt>' . t('How to use') . '</dt>';
      $output .= '<dd>' . t("You can add the field to any entity (eg. content type, users, ..) as usual. After you applied the field you have to configure how its output should be filtered (eg. Filtered HTML, Plain Text). Also it is recommended to set the number of values to unlimited.") . '</dd>';
      $output .= '<dt>' . t('Formatters') . '</dt>';
      $output .= '<dd>' . t("You have the choise of two display formatters: jQuery accordion (animated show / hide) and simple text (none formatted, simple output for custom theming). If you are using accordion you can modify its behaviour easily by the display settings.") . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function faqfield_field_info() {
  return array(
    'faqfield' => array(
      'label' => t('FAQ Field'),
      'description' => t('Field for frequently asked questions.'),
      'default_widget' => 'faqfield_textboxes',
      'default_formatter' => 'faqfield_accordion',
    ),
  );
}

/**
 * Implements hook_field_settings_form().
 */
function faqfield_field_settings_form($field, $instance, $has_data) {
  $form = array();

  // Get a list of formats that the current user has access to.
  $formats = filter_formats();
  foreach ($formats as $format) {
    $options[$format->format] = $format->name;
  }

  // Format select input for field settings.
  $form['format'] = array(
    '#type' => 'select',
    '#title' => t('Default text format'),
    '#default_value' => @$field['settings']['format'],
    '#options' => $options,
    '#access' => count($formats) > 1,
    '#required' => TRUE,
    '#description' => t('Default format to filter FAQ field content.'),
  );

  // Input for the count of rows for the answer field.
  $form['answer_widget'] = array(
    '#type' => 'select',
    '#title' => t('Answer widget'),
    '#default_value' => isset($field['settings']['answer_widget']) ? $field['settings']['answer_widget'] : 'textarea',
    '#options' => array('textarea' => t('Textarea'), 'text_format' => t('Formatable textarea'), 'textfield' => t('Textfield')),
    '#required' => TRUE,
    '#description' => t('What form widget to use for answer input. Formatable textarea is needed for WYSIWYG editors.'),
  );

  // Input for the count of rows for the answer field.
  $form['answer_rows'] = array(
    '#type' => 'select',
    '#title' => t('Answer rows'),
    '#default_value' => isset($field['settings']['answer_rows']) ? $field['settings']['answer_rows'] : 3,
    '#options' => array(1 => '1', 2 => '2', 3 => '3', 4 => '4', 5 => '5'),
    '#required' => TRUE,
    '#description' => t('Number of rows used for the answer textarea.'),
    '#states' => array(
      'invisible' => array(
        ':input[id="edit-field-settings-answer-widget"]' => array('value' => 'textfield'),
      ),
    ),
  );

  return $form;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function faqfield_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = '';

  // Accordion display settings summary.
  if ($display['type'] === 'faqfield_accordion') {
    $summary_elements = array();
    if ($settings['active'] !== '') {
      $summary_elements[] = t('Active: @element', array('@element' => $settings['active']));
    }
    if ($settings['autoHeight']) {
      $summary_elements[] = t('Auto height');
    }
    if ($settings['collapsible']) {
      $summary_elements[] = t('Collapsible');
    }
    $summary_elements[] = t('Event: @event', array('@event' => $settings['event']));
    $summary = implode(', ', $summary_elements);
  }

  return $summary;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function faqfield_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $element = array();

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  // Accordion display settings.
  if ($display['type'] === 'faqfield_accordion') {
    // Number of first active element.
    $element['active'] = array(
      '#type' => 'textfield',
      '#title' => t('Active'),
      '#default_value' => $settings['active'],
      '#description' => t('Index of active element. Leave empty to display none at start.'),
      // @TODO _element_validate_number() is deprecated since 7.8.
      // Need to switch to element_validate_number() when most people updated.
      // '#element_validate' => array('element_validate_number'),
      // Currently using fallback functionality:
      '#element_validate' => array(function_exists('element_validate_number') ? 'element_validate_number' : '_element_validate_number'),
      '#maxlength' => 3,
      '#size' => 5,
    );
    // Whether auto heigth is enabled.
    $element['autoHeight'] = array(
      '#type' => 'checkbox',
      '#title' => t('Auto height'),
      '#default_value' => $settings['autoHeight'],
      '#description' => t('If set, the highest content part is used as height reference for all other parts. Provides more consistent animations.'),
    );
    // Whether elements are collabsible.
    $element['collapsible'] = array(
      '#type' => 'checkbox',
      '#title' => t('Collapsible'),
      '#default_value' => $settings['collapsible'],
      '#description' => t('Whether an opened question can be collapsed (by the triggering event).'),
    );
    // Name of triggering event.
    $element['event'] = array(
      '#type' => 'textfield',
      '#title' => t('Event'),
      '#default_value' => $settings['event'],
      '#description' => t('The event on which to trigger the accordion.'),
      '#maxlength' => 10,
    );
  }
  return $element;
}

/**
 * Implements hook_field_is_empty().
 */
function faqfield_field_is_empty($item, $field) {
  return empty($item['question']) || empty($item['answer']);
}

/**
 * Implements hook_field_formatter_info().
 */
function faqfield_field_formatter_info() {
  return array(
    // This formatter uses jQuery accordion widget.
    'faqfield_accordion' => array(
      'label' => t('Accordion'),
      'field types' => array('faqfield'),
      'settings' => array(
        'active' => 0,
        'autoHeight' => TRUE,
        'collapsible' => FALSE,
        'event' => 'click',
      ),
    ),
    // This formatter just displays the FAQ content as simple text.
    'faqfield_simple_text' => array(
      'label' => t('Simple text'),
      'field types' => array('faqfield'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function faqfield_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {

    // This formatter adds jQuery accordion widget.
    // This will not be themeable, because changes would break
    // jQuery UI accordion functionality!
    case 'faqfield_accordion':

      $faqfield_id = 'faqfield_' . $field['field_name'];

      // Add jQuery UI accordion library.
      drupal_add_library('system', 'ui.accordion');
      drupal_add_js('jQuery(function(){jQuery("#' . $faqfield_id . '").accordion(Drupal.settings.' . $faqfield_id . ');});', 'inline');
      // We need to convert the element active value to an integer for jQuery.
      if ($display['settings']['active'] !== '') {
        settype($display['settings']['active'], 'int');
      }
      // If setting was left blank, we set FALSE so no element will be active.
      else {
        $display['settings']['active'] = FALSE;
      }
      // Set accordion display settings.
      drupal_add_js(array($faqfield_id => $display['settings']), 'setting');

      // We need to put all of this within a single piece of markup,
      // otherwise this would not work with jQuery accordion.
      $element[0]['#markup'] = '<div id="' . $faqfield_id . '">';
      foreach ($items as $item) {
        // Decide whether to use the default format or the custom one.
        $format = isset($item['answer_format']) ? $item['answer_format'] : @$field['settings']['format'];
        // Build the markup.
        $element[0]['#markup'] .= '<h3 class="faqfield-question"><a href="#">' . check_markup($item['question'], $format) . '</a></h3>';
        $element[0]['#markup'] .= '<div class="faqfield-answer">' . check_markup($item['answer'], $format) . '</div>';
      }
      $element[0]['#markup'] .= '</div>';
      break;

    // This themeable formatter displays the FAQ content as simple text.
    case 'faqfield_simple_text':
      foreach ($items as $delta => $item) {
        // Decide whether to use the default format or the custom one.
        $format = isset($item['answer_format']) ? $item['answer_format'] : @$field['settings']['format'];
        // Add them as page elements, they'll be rendered automatically later.
        $element[$delta] = array(
          '#theme' => 'faqfield_formatter',
          // Filter values before passing them to the template.
          '#question' => check_markup($item['question'], $format),
          '#answer' => check_markup($item['answer'], $format),
        );
      }
      break;

  }
  return $element;
}

/**
 * Implements hook_theme().
 */
function faqfield_theme() {
  // Themeable simple text formatter.
  return array(
    'faqfield_formatter' => array(
      'variables' => array('question' => NULL, 'answer' => NULL),
    ),
  );
}

/**
 * Returns HTML for a faqfield formatter.
 *
 * @param array $variables
 *   An associative array containing:
 *   - question
 *   - answer
 */
function theme_faqfield_formatter($variables) {
  $output = '<h3 class="faqfield-question">' . $variables['question'] . '</h3>';
  $output .= '<div class="faqfield-answer">' . $variables['answer'] . '</div>';
  return $output;
}

/**
 * Implements hook_field_widget_info().
 */
function faqfield_field_widget_info() {
  return array(
    // Simple text inputs.
    'faqfield_textboxes' => array(
      'label' => t('FAQ Field'),
      'field types' => array('faqfield'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function faqfield_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $base = $element;
  if ($instance['widget']['type'] === 'faqfield_textboxes') {

    // Add textfield for question.
    $element['question'] = array(
      '#title' => t('Question'),
      '#type' => 'textfield',
      '#default_value' => isset($items[$delta]['question']) ? $items[$delta]['question'] : '',
      '#maxlength' => 255,
      '#delta' => $delta,
      '#weight' => 0,
    ) + $base;

    // Add textarea / formatable textarea / textfield for answer.
    $element['answer'] = array(
      '#title' => t('Answer'),
      '#type' => isset($field['settings']['answer_widget']) ? $field['settings']['answer_widget'] : 'textarea',
      '#default_value' => isset($items[$delta]['answer']) ? $items[$delta]['answer'] : '',
      '#delta' => $delta,
      '#weight' => 1,
      '#format' => isset($items[$delta]['answer_format']) ? $items[$delta]['answer_format'] : @$field['settings']['format'],
      '#rows' => @$field['settings']['answer_rows'],
    ) + $base;

    // Add custom element validation handler for handling text format widgets.
    if (@$field['settings']['answer_widget'] == 'text_format') {
      $element['answer']['#element_validate'][] = 'faqfield_field_widget_answer_element_validate';
    }
  }
  return $element;
}

/**
 * Validation callback for faqfield widget form.
 *
 * Normal textarea's and textfields put their values simply in by
 * array($name => $value); Unfortunately text_format textareas put
 * them into an array so also the format gets saved: array($name
 * => array('value' => $value, 'format' => $format)).
 * So the API will try to save normal textfields to the 'name' field
 * and text_format fields to 'answer_value' and 'answer_format'.
 * To bypass this, we pull the values out of this array and force
 * them to be saved in 'answer' and 'answer_format'.
 */
function faqfield_field_widget_answer_element_validate($element, &$form_state) {
  foreach ($form_state['values'][$element['#field_name']] as &$lang_values) {
    foreach ($lang_values as &$values) {
      if (is_array($values['answer'])) {
        $values['answer_format'] = $values['answer']['format'];
        $values['answer'] = $values['answer']['value'];
      }
    }
  }
}
